eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://xuesemofa:wangzheshengcun@39.106.33.113:9002/eureka/
    status-page-url: ${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html

server:
  port: 9005
  tomcat: 
    uri-encoding: UTF-8

spring:
  application:
      name: business

  datasource:
    url: jdbc:mysql://localhost:3306/jpt?useUnicode=true&characterEncoding=ISO-8859-1&useSSL=false
    username: root
    password: cp9*:s.%sf
    driver-class-name: com.mysql.jdbc.Driver

  jmx:
    default-domain: business

logging:
  file: business.log
  level:
    org:
      account:
        com: debug

page:
  size: 15